Hello

In [4]:
arr = [1,2,3,4]
print (arr)

[1, 2, 3, 4]


In [5]:
print ('Help')

Help


In [6]:
arr

[1, 2, 3, 4]

In [8]:
a = 2
b = 3
print('Value of a is '+ str(a) + ' and b is ' + str(b))

Value of a is 2 and b is 3


In [9]:
type(a)

int

In [12]:
s1 = 'Hello World'
type(s1)

str

In [16]:
$y=x^2$
print y

SyntaxError: ignored

https://numpy.org/doc/stable/user/whatisnumpy.

$y=x^2$

In [18]:
a=[1,2,3,4,5,6,7,8]
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [19]:
type(a)

list

In [20]:
b=[8,7,6,5,4,3,2,1]
b

[8, 7, 6, 5, 4, 3, 2, 1]

In [21]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

In [22]:
c

[8, 14, 18, 20, 20, 18, 14, 8]

In [23]:
import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

Sleeping
Done Sleeping


In [25]:
import numpy as np.add_newdoc


https://colab.research.google.com/notebooks/basic_features_overview.ipynb#scrollTo=odfM-_GxWbCy

In [27]:
%%html
<marquee style='width: 30%; color: blue;'><b>Hello World!</b></marquee>

https://numpy.org/doc/stable/user/quickstart.html

In [31]:
import numpy as np
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
a.dtype.name

'int64'

In [36]:
a.itemsize

8

In [37]:
a.size

15

In [38]:
type(a)

numpy.ndarray

In [41]:
b = np.array([2,3,4])

In [42]:
b

array([2, 3, 4])

In [45]:
b = np.array([[2,3,4],[6,6,3,5]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [46]:
b

array([list([2, 3, 4]), list([6, 6, 3, 5])], dtype=object)

In [47]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
d = np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [ ]:
b