In [9]:
import numpy as np

In [2]:
list1 = list(range(10))
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(list1)

list

In [20]:
import array as ar
L = list(range(10))
A = ar.array('i',L)
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.array([range(i,i+4) for i in [2,4,6,8]])


array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((2,5),dtype= float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,5),dtype= float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((3,5),3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [19]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
np.array((i,i+0.5)for i in [0,1]

SyntaxError: ignored

In [26]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.random.random((3,4))

array([[0.15670655, 0.24661678, 0.78162059, 0.69482804],
       [0.25132883, 0.91123915, 0.21671631, 0.47229127],
       [0.37956903, 0.23691309, 0.27461913, 0.61036909]])

In [30]:
np.random.normal(0,1,(3,3))

array([[-0.54963809, -0.1765569 ,  0.37244848],
       [ 1.13103591, -0.86488137, -1.12521918],
       [-0.4853753 , -1.62984138, -0.41713986]])

In [31]:
np.random.randint(0,10,(3,3))

array([[0, 7, 9],
       [3, 0, 1],
       [7, 7, 8]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.empty(3)

array([1., 1., 1.])

In [38]:
np.random.seed(20)
x1 = np.random.randint(10,size=6)
x1

array([3, 9, 4, 6, 7, 2])

In [42]:
np.random.seed(100)
x2 = np.random.randint(200,size=(3,2,5,2,2))
x2

array([[[[[  8,  24],
          [ 67, 103]],

         [[ 87,  79],
          [176, 138]],

         [[ 94, 180],
          [ 98,  53]],

         [[ 66,  14],
          [ 34,  24]],

         [[143, 107],
          [ 60,  58]]],


        [[[144, 137],
          [ 93,  86]],

         [[130, 155],
          [108, 132]],

         [[159, 129],
          [141, 100]],

         [[  4,  91],
          [187,  67]],

         [[135,  49],
          [175, 193]]]],



       [[[[ 61,  14],
          [183, 199]],

         [[ 80,   2],
          [121, 105]],

         [[147,  63],
          [181,  27]],

         [[ 56, 113],
          [158, 176]],

         [[ 47, 167],
          [109,  38]]],


        [[[172,  18],
          [192, 184]],

         [[162, 181],
          [ 17,  72]],

         [[ 13, 106],
          [ 30,  17]],

         [[ 53,  68],
          [178,  91]],

         [[181,  78],
          [  0,  13]]]],



       [[[[185, 106],
          [131,  70]],

         [[131, 138],


In [43]:
x2.shape

(3, 2, 5, 2, 2)

In [44]:
x2.ndim

5

In [45]:
x2.size

120

In [46]:
x2.nbytes

960

In [47]:
x2.itemsize

8